server:
  port: 16000

spring:
  application:
    name: service-house
  profiles:
    active: dev   #开发环境，这里是dev
  cloud:
    nacos:
      server-addr: yd.haotchen.top:8858 # Nacos地址
      config:
        file-extension: yaml # 文件后缀名

  datasource:
    username: root
    password: a@199862
    url: jdbc:mysql://haotchen.top:36000/hsms
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      # 最小连接数
      minimum-idle: 10
      # 最大连接数
      maximum-pool-size: 100
      # 自动提交
      auto-commit: true
      # 链接超时时间
      connection-timeout: 30000
      # 链接的状态保持时间
      idle-timeout: 60000
      # 一个链接的最大时长
      max-lifetime: 60000
      # 测试链接
      connection-test-query: SELECT 1

    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

fdfs:
  so-timeout: 2000 # 读取时间
  connect-timeout: 1000 # 连接超时时间
  thumb-image: # 生成缩略图
    height: 150 # 缩略图高度
    width: 150 # 缩略图宽度
  tracker-list: # tracker 服务器地址
    - yd.haotchen.top:22122
  web-server-url: http://haotchen.top:9000/ # storage 服务器上nginx的地址
  pool: # 可参考 ConnectionPoolConfig
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数  key配置的是连接服务端的地址(IP+端口)连接情况，如果有连接不够用的情况可以调整以上参数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5
    #向调用者输出“连接”资源时，是否检测有效性
    test-on-borrow: true
fileServer:
  url: http://haotchen.top:9000/