auth:
  secret: '123123'

spring:
  application:
    name: service-auth
  profiles:
    active: dev   #开发环境，这里是dev
  cloud:
    nacos:
      server-addr: yd.haotchen.top:8858 # Nacos地址
      config:
        file-extension: yaml # 文件后缀名
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 12000